language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  # typing is required for python2.7 only
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install typing; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install mypy==0.620; fi
  - pip install -e .
  - pip install pytest
  - ln -s test.PixivDBManager.py test_PixivDBManager.py
  - ln -s test.PixivHelper.py test_PixivHelper.py
  - ln -s test.PixivModel.whitecube.py test_PixivModel_whitecube.py
  - ln -s test.updateHtml.py test_updateHtml.py
# command to run tests
script:
  - ln -s test.PixivModel.py test_PixivModel.py
  - pytest -v -W error::UserWarning ./test_*
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then mypy --ignore-missing-imports *.py; fi
